### ISSUE TITLE
npm v1.0.2 of this package is broken

### ISSUE THREAD

**Issue by alisdairjsmyth** [klarstil/lifx-http-api#4]
`package.json` included in npm install does not reflect commit [fb476c682da02e10c2321a8d4494d6aed601f37f](https://github.com/klarstil/lifx-http-api/commit/fb476c682da02e10c2321a8d4494d6aed601f37f), so main is expected to be `source/lifx.js` which no longer exists.

**Comment by sburr** [comment]
This is still broken in the npmjs.org package. What is more, the fix here maintains the same version number, making the working (source) version indistinguishable from the broken (packaged) version.

Can you publish the fixed version up to npmjs.org with an updated semver?

**Comment by klarstil** [comment]
Hey @alisdairjsmyth & @sburr thanks for the heads up, I bumped up the version to 1.0.3 and published a new package. I hope this fixes your issue.

**Comment by sburr** [comment]
Thanks!
